name: Integration
on:
  push:
jobs:
  solidity:
    name: Solidity
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install dependencies
        run: npm ci

      - run: npx hardhat compile

      - name: Check lint
        # XXX: required for https://github.com/crytic/slither-action/issues/4 until
        # next release
        uses: tlvince/slither-action@031cc490cae6e86d3364fb10efea5a580cb8c1c8
        id: slither
        continue-on-error: true
        with:
          ignore-compile: true
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}

      - run: echo '${{ steps.slither.outputs.stdout }}'

      - name: Create/update checklist as PR comment
        uses: actions/github-script@v5.1.0
        if: github.event_name == 'pull_request'
        with:
          script: |
            const script = require('.github/scripts/comment')
            const header = '# Slither report'
            const body = '${{ steps.slither.outputs.stdout }}'
            await script({ github, context, header, body })
